default: &default
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000
  username: whatevs
  password:

development:
  <<: *default
  database: python-no-thanks_development

test:
  <<: *default
  database: python-no-thanks_test

production:
  <<: *default
