default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: mumslink_development

test:
  <<: *default
  database: mumslink_test

production:
  <<: *default
