default: &default
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000
  username: workshops
  password:

development:
  <<: *default
  database: python_no_thanks_development

test:
  <<: *default
  database: python_no_thanks_test

production:
  <<: *default
